// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POC.ThomasGreg.Cadastro.Infra.SqlServer;

#nullable disable

namespace POC.ThomasGreg.Cadastro.Infra.SqlServer.Migrations
{
//    [DbContext(typeof(CadastroDbContext))]
//    partial class CadastroDbContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "9.0.1")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128);

//            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

//            modelBuilder.Entity("POC.ThomasGreg.Cadastro.Domain.Features.Cliente.Entidades.ClienteVO", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

//                    b.Property<string>("Email")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.Property<byte[]>("Logotipo")
//                        .IsRequired()
//                        .HasColumnType("varbinary(max)");

//                    b.Property<string>("Nome")
//                        .IsRequired()
//                        .HasMaxLength(100)
//                        .HasColumnType("nvarchar(100)");

//                    b.HasKey("Id");

//                    b.ToTable("Clientes", (string)null);
//                });

//            modelBuilder.Entity("POC.ThomasGreg.Cadastro.Domain.Features.Cliente.Entidades.LogradouroVO", b =>
//                {
//                    b.Property<long>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasColumnType("bigint");

//                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

//                    b.Property<long?>("ClienteVOId")
//                        .HasColumnType("bigint");

//                    b.Property<string>("Nome")
//                        .IsRequired()
//                        .HasColumnType("nvarchar(max)");

//                    b.HasKey("Id");

//                    b.HasIndex("ClienteVOId");

//                    b.ToTable("LogradouroVO");
//                });

//            modelBuilder.Entity("POC.ThomasGreg.Cadastro.Domain.Features.Cliente.Entidades.LogradouroVO", b =>
//                {
//                    b.HasOne("POC.ThomasGreg.Cadastro.Domain.Features.Cliente.Entidades.ClienteVO", null)
//                        .WithMany("Logradouros")
//                        .HasForeignKey("ClienteVOId");
//                });

//            modelBuilder.Entity("POC.ThomasGreg.Cadastro.Domain.Features.Cliente.Entidades.ClienteVO", b =>
//                {
//                    b.Navigation("Logradouros");
//                });
//#pragma warning restore 612, 618
//        }
//    }
}
